config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/about', to: 'homes#about', as: 'about'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [ :index, :show, :edit, :update, :destroy]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user

validates :shop_name, presence: true
validates :caption, presence: true
validates :image, presence: true

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

validates :name, presence: true


  has_many :posts, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @posts = Post.all
  end

  def about
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action  :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @post = Post.new

  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end



  def index
     @posts = Post.all
     @user = current_user
    # @book = Book.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

 private

  def post_params
    params.require(:post).permit(:shop_name, :image, :caption)
  end

  def is_matching_login_user
    @post = Post.find(params[:id])
    if @post.user_id != current_user.id
    redirect_to posts_path
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]


  def new
     @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    @user.save
    redirect_to users_path
  end


  def index
     @users = User.all
     @user = current_user
    # @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  def destroy
  end

 private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end


  def is_matching_login_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
    redirect_to user_path(current_user.id)
    end
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="row">
  <div class="col-md-10 offset-2" >
    <h1>About</h1>
  </div>
  <div class="col-md-8 offset-2">
    <div class="card-body">
        <p>このサイトは、飼っている猫の日常や道端や猫カフェなどで出会った猫たちの様子や感想を投稿するサイトです。</p>
        <h4>主な利用シーン</h4>
        <ul>
        <li>猫の可愛い姿を写真に収めたとき</li>
        <li>猫に会うことが出来ないとき</li>
        <li>日頃他の人はどのように猫と一緒にいるのか気になったとき</li>
        </ul>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="row">
<% @posts.each do |post| %>
  <div class="col-md-4">
    <div class="card">
      <%= link_to  post_path(post.id) do %>
      <%= image_tag post.get_image, class:"card-img-top" %>
      <% end %>
      <div class="card-body">
        <p>タイトル：<%= post.shop_name %></p>
        <p>説明：<%= post.caption %></p>
        <p>投稿ユーザー<%= image_tag post.user.get_profile_image, width:"px" %><%= post.user.name %></p>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/cab7334bd1.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light" style="background-color: #e3f2fd;">
        <a class="navbar-brand" href="/">猫吸い</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

    <% if user_signed_in? %>

      <li class="nav-item active">
        <%= link_to new_post_path, class:"nav-link" do %>
        <i class="fa-solid fa-paw"></i>
        投稿フォーム
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to posts_path, class:"nav-link" do %>
        <i class="fa-solid fa-shield-cat"></i>
        投稿一覧
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to user_path(current_user.id), class:"nav-link" do %>
        <i class="fa-solid fa-cat"></i>
        マイページ
        <% end %>
        </li>

      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete,class:"nav-link" do %>
         <i class="fa-solid fa-right-from-bracket"></i>
        ログアウト
        <% end %>
      </li>

    <% else %>
      <li class="nav-item">
        <%= link_to about_path, class:"nav-link"  do %>
         <i class="fa-solid fa-user-plus"></i>
         アバウト
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_user_registration_path, class:"nav-link"  do %>
         <i class="fa-solid fa-user-plus"></i>
         新規登録
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to new_user_session_path,class:"nav-link"  do %>
        <i class="fa-solid fa-right-to-bracket"></i>
        ログイン
        <% end %>
      </li>
    <% end %>

    </ul>
    </div>
    </nav>
  </header>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-4">

<h1>編集</h1>
<%= form_with model: @post do |f| %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  <h4>タイトル</h4>
  <%= f.text_field :shop_name,class:"form-control"  %>
  <h4>説明</h4>
  <%= f.text_area :caption,class:"form-control"  %>
  <%= f.submit '更新' ,class:"btn btn-success" %>
<% end %>

    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
<% @posts.each do |post| %>
  <div class="col-md-4">
    <div class="card">
      <%= link_to  post_path(post.id) do %>
      <%= image_tag post.get_image, class:"card-img-top" %>
      <% end %>
      <div class="card-body">
        <p>タイトル：<%= post.shop_name %></p>
        <p>説明：<%= post.caption %></p>
        <p>投稿ユーザー<%= image_tag post.user.get_profile_image, width:"px" %><%= post.user.name %></p>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-4">
      <h1>新規投稿</h1>
        <% if @post.errors.any? %>
        <%= @post.errors.count %>件のエラーが発生しました
          <ul>
            <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with model: @post do |f| %>

          <h4>画像</h4>
          <%= f.file_field :image, accept: "image/*" %>
          <h4>タイトル</h4>
          <%= f.text_field :shop_name ,class:"form-control" %>
          <h4>説明</h4>
          <%= f.text_area :caption,class:"form-control" %>
          <%= f.submit '投稿' ,class:"btn btn-primary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-4">
      <%= image_tag @post.get_image,width:"100%" %>
        <p>タイトル：<%= @post.shop_name %></p>
        <p>説明：<%= @post.caption %></p>
        <p>ユーザー：<%= image_tag @post.user.get_profile_image %></p>
        <p>ユーザーネーム：<%= @post.user.name %></p>
        <p>投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>

      <% if current_user == @post.user %>
        <%= link_to edit_post_path(@post.id),class:"nav-link"  do %>
        <i class="fa-regular fa-pen-to-square"></i>
          編集
        <% end %>

        <%= link_to post_path(@post.id), method: :delete ,class:"nav-link"  do %>
        <i class="fa-solid fa-trash-can"></i>
          削除
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-4">
      <h2>プロフィール編集</h2>
      <%= form_with model: @user do |f| %>
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" ,class:"form-control" %>
          <label for="inputImage">ProfileImage</label>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          <%= f.submit "変更を保存" ,class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-4">
      <!-- ここにスケジュール -->
      <h3><%= @user.name %></h3>
      <%= image_tag @user.get_profile_image %>
      <% if current_user == @user %>
        <%= link_to edit_user_path(@user.id),class:"nav-link" do %>
          <i class="fa-regular fa-pen-to-square"></i>
          編集
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-4">
        <%= link_to post_path(post.id) do %>
          <div class="card">
          <%= image_tag post.get_image, class:"card-img-top" %>
            <div class="card-body">
              <p>投稿ユーザー画像<%#= image_tag post_image.user.get_profile_image(100,100) %></p>
              <p>ショップ名：<%= post.shop_name %></p>
              <p>説明：<%= post.caption %></p>
              <p>ユーザーネーム：<%= @user.name %></p>
            </div>
           </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>